### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by plasticchris** [ndechesne/qcom-oe-manifest#3]
What's the difference between this one and oe-rpb-manifest ?

**Comment by ndechesne** [comment]
the qcom-oe-manifest can be used to build OE-core + meta-qcom , only. No other dependency. I typically use that for testing OE core when submitting patches. it only brings the QCOM BSP on top of vanilla OpenEmbedded Core.

oe-rpb-manifest is a full featured 'product' that we support at Linaro , and provides a reference distro implementation for many 96boards.
